######### Variáveis de ambiente
@token = "MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx"

######### Cadastro de Mensagem
POST http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx

{
    "title": "Eu acho que o hexa vem!!!",
    "message": "Novo comentário inserido!"
}

######### Listar todos as Mensagens
GET http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx

######### Listar Mensagem específica
GET http://127.0.0.1:3333/messages/14 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx

######### Alterar Mensagem
PUT http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "title": "O Neymar tá jogando muito!!!",
    "message": "Comentário alterado!"
}

######### Apagar Mensagem
DELETE http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}