######### Cadastro Tópico
POST http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx

{
    "name": "Topico1"
}

######### Listar todos os Tópico
GET http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx


######### Listar Tópico específico
GET http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx

######### Alterar Tópico
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx

{
    "name": "Topico II"
}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.yAS0ht2Huy8qNg4S0pWjHuQ0IYTuk5hFXWbJeopp7HFrKwahV7QVoYzLqYAx
